-- S1
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL REPEATABLE READ;

-- S2
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL REPEATABLE READ;

-- S1
BEGIN;

-- S2
BEGIN;

-- S1
SELECT SUM(rating)
FROM pizzeria;

-- S2
INSERT INTO pizzeria (id, name, rating) VALUES (11, 'Kazan Pizza 2', 4);

COMMIT;

-- S1
SELECT SUM(rating) FROM pizzeria;

COMMIT;

-- S1
SELECT SUM(rating) FROM pizzeria;

-- S2
SELECT SUM(rating) FROM pizzeria;